#!/usr/bin/env node
// Copyright (c) 2024-2026 nich (@nichxbt). All rights reserved.
// Generates dashboard/js/navdata.js: the command-palette route index, built
// from the pages that actually ship. Run in the site build pipeline.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const DASH = path.join(ROOT, 'dashboard');

// Curated primary destinations (shown first, with icons)
const PRIMARY = [
  ['/', 'Home', '\u{1F3E0}'], ['/features', 'Features', '✨'],
  ['/docs', 'Documentation', '\u{1F4DA}'], ['/tutorials', 'Tutorials', '\u{1F393}'],
  ['/scripts', 'Browser Scripts', '\u{1F4CB}'], ['/mcp', 'AI / MCP Server', '\u{1F916}'],
  ['/pricing', 'Pricing', '\u{1F4B8}'], ['/blog', 'Blog', '✍️'],
  ['/changelog', 'Changelog', '\u{1F4E3}'], ['/faq', 'FAQ', '❓'],
  ['/compare', 'Compare', '⚖️'], ['/about', 'About', 'ℹ️'],
  ['/contact', 'Contact', '✉️'], ['/status', 'Status', '\u{1F4E1}'],
];
const primarySet = new Set(PRIMARY.map((p) => p[0]));

function clean(rel) {
  let u = '/' + rel.replace(/\.html$/, '').split(path.sep).join('/');
  return u.replace(/\/index$/, '') || '/';
}
function titleFromFile(file) {
  try {
    const html = fs.readFileSync(file, 'utf-8').slice(0, 4000);
    const m = html.match(/<title>([^<]+)<\/title>/i);
    if (m) return m[1].replace(/\s*[|–—-].*$/, '').replace(/\s*– XActions.*/, '').trim();
  } catch {}
  return null;
}
function* walk(dir) {
  for (const d of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, d.name);
    if (d.isDirectory()) yield* walk(full);
    else if (d.name.endsWith('.html') && !d.name.startsWith('_')) yield full;
  }
}

const secondary = [];
const EXCLUDE = new Set(['/404', '/50x', '/admin', '/dashboard']);
for (const file of walk(DASH)) {
  const url = clean(path.relative(DASH, file));
  if (url === '/index') continue;
  if (primarySet.has(url) || EXCLUDE.has(url)) continue;
  let section = 'Page';
  if (url.startsWith('/docs/')) section = 'Docs';
  else if (url.startsWith('/scripts/')) section = 'Script';
  else if (url.startsWith('/tutorials/')) section = 'Tutorial';
  else if (url.startsWith('/blog/')) section = 'Blog';
  const title = titleFromFile(file) || url.split('/').pop().replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  secondary.push({ u: url, t: title, s: section });
}
secondary.sort((a, b) => a.t.localeCompare(b.t));

const primary = PRIMARY.map(([u, t, i]) => ({ u, t, i, s: 'Go to' }));
const out = `// Auto-generated by scripts/build-navdata.js — do not edit.\nwindow.XA_NAV=${JSON.stringify({ primary, secondary })};\n`;
fs.writeFileSync(path.join(DASH, 'js', 'navdata.js'), out);
console.log(`navdata.js: ${primary.length} primary + ${secondary.length} pages`);
